export interface GalleryImage {
  id: string;
  src: string;
  alt: string;
  eventId: string;
  eventTitle: string;
  date: string;
  year: number;
  location: string;
  aspectRatio: 'portrait' | 'landscape';
}

export interface GalleryEvent {
  id: string;
  title: string;
  date: string;
  year: number;
  location: string;
  description: string;
}

export const galleryEvents: GalleryEvent[] = [
  {
    id: 'menstrual-hygiene-hope-high-2026',
    title: 'Menstrual Hygiene Day - Hope High',
    date: 'June 9, 2026',
    year: 2026,
    location: 'Hope High Academy, Zawan',
    description: 'Outreach and distribution session focused on biological health education and sanitary pads distribution at Hope High Academy.'
  },
  {
    id: 'tcnn-partnership-2026',
    title: 'Official Partnership with TCNN',
    date: 'May 2026',
    year: 2026,
    location: 'TCNN Bukuru, Plateau State',
    description: 'Launch of the official partnership and advocacy collaboration between ECJAPI and the Theological College of Northern Nigeria (TCNN) in Bukuru.'
  },
  {
    id: 'first-time-lunch-stable-hands-2026',
    title: 'First Time Lunch - Female Stable Hands',
    date: 'July 8, 2026',
    year: 2026,
    location: 'Plateau State, Nigeria',
    description: 'Special luncheon, counseling, and reproductive wellness mentorship session organized for female stable hands.'
  },
  {
    id: 'padded-girl-campaign-2026',
    title: 'De-Stigmatizing Menstrual Development, Dismantles Rape Culture Campaign',
    date: 'May 28, 2026',
    year: 2026,
    location: 'Schools across Bukuru & Zawan',
    description: 'Signature week-long awareness program led by Jennifer Nikurai Maton (Founder, ECJAPI) and Felicia Samson (TVAII).'
  },
  {
    id: 'horsemanship-closing-ceremony-2025',
    title: 'Stablehand & Horsemanship Closing Ceremony & Fundraiser',
    date: 'January 9-11, 2025',
    year: 2025,
    location: 'Plateau State, Nigeria',
    description: "Nigeria's first ever Female Stablehand & Horsemanship Training Program closing ceremony & fundraiser. Celebrated with Nigeria's first ever ALL-FEMALE Polo game between Amazonian Reins and Rein Rebels, featuring women in all roles from commentators to bouncers."
  },
  {
    id: 'how-the-story-began-2024',
    title: 'How the Story Began',
    date: 'May 2024',
    year: 2024,
    location: 'Bukuru, Plateau State',
    description: 'Tracing the initial community workshops, group meetings, and grassroots advocacy circles that started ECJAPI.'
  }
];

export const galleryImages: GalleryImage[] = [
  // 1. Menstrual Hygiene Day - Hope High (2026) - WeTransfer Previews
  {
    id: 'stlkcl5wpnb4p6b0w20260609143909',
    src: '/menstrual_hygiene_hope_high_2026/stlkcl5wpnb4p6b0w20260609143909.webp',
    alt: 'Menstrual Hygiene Day presentation and activities - School H-24',
    eventId: 'menstrual-hygiene-hope-high-2026',
    eventTitle: 'Menstrual Hygiene Day - Hope High',
    date: 'June 9, 2026',
    year: 2026,
    location: 'Hope High Academy, Zawan',
    aspectRatio: 'landscape'
  },
  {
    id: 's3l8hp8hxmqswevdt20260609143905',
    src: '/menstrual_hygiene_hope_high_2026/s3l8hp8hxmqswevdt20260609143905.webp',
    alt: 'Hope High Academy students engaging during the Q&A session - School H-25',
    eventId: 'menstrual-hygiene-hope-high-2026',
    eventTitle: 'Menstrual Hygiene Day - Hope High',
    date: 'June 9, 2026',
    year: 2026,
    location: 'Hope High Academy, Zawan',
    aspectRatio: 'landscape'
  },
  {
    id: 'sck5ejziyk1wi6h2b20260609143905',
    src: '/menstrual_hygiene_hope_high_2026/sck5ejziyk1wi6h2b20260609143905.webp',
    alt: 'Educational biological chart showing female reproductive development - School H-26',
    eventId: 'menstrual-hygiene-hope-high-2026',
    eventTitle: 'Menstrual Hygiene Day - Hope High',
    date: 'June 9, 2026',
    year: 2026,
    location: 'Hope High Academy, Zawan',
    aspectRatio: 'landscape'
  },
  {
    id: 'siwra1edh900fj4ku20260609143905',
    src: '/menstrual_hygiene_hope_high_2026/siwra1edh900fj4ku20260609143905.webp',
    alt: 'Speakers demonstrating menstrual hygiene techniques - School H-27',
    eventId: 'menstrual-hygiene-hope-high-2026',
    eventTitle: 'Menstrual Hygiene Day - Hope High',
    date: 'June 9, 2026',
    year: 2026,
    location: 'Hope High Academy, Zawan',
    aspectRatio: 'landscape'
  },
  {
    id: 'se7m9nh22x4h0lncl20260609143905',
    src: '/menstrual_hygiene_hope_high_2026/se7m9nh22x4h0lncl20260609143905.webp',
    alt: 'Distribution of sanitary pads to Hope High students - School H-28',
    eventId: 'menstrual-hygiene-hope-high-2026',
    eventTitle: 'Menstrual Hygiene Day - Hope High',
    date: 'June 9, 2026',
    year: 2026,
    location: 'Hope High Academy, Zawan',
    aspectRatio: 'landscape'
  },
  {
    id: 'sni7cb4z5510a5ay420260609143905',
    src: '/menstrual_hygiene_hope_high_2026/sni7cb4z5510a5ay420260609143905.webp',
    alt: 'Students smiling during the interactive activities - School H-30',
    eventId: 'menstrual-hygiene-hope-high-2026',
    eventTitle: 'Menstrual Hygiene Day - Hope High',
    date: 'June 9, 2026',
    year: 2026,
    location: 'Hope High Academy, Zawan',
    aspectRatio: 'landscape'
  },
  {
    id: 'si58trk5r4bl6p0mr20260609143905',
    src: '/menstrual_hygiene_hope_high_2026/si58trk5r4bl6p0mr20260609143905.webp',
    alt: 'Presenters answering student questions on emotional health - School H-29',
    eventId: 'menstrual-hygiene-hope-high-2026',
    eventTitle: 'Menstrual Hygiene Day - Hope High',
    date: 'June 9, 2026',
    year: 2026,
    location: 'Hope High Academy, Zawan',
    aspectRatio: 'landscape'
  },
  {
    id: 'supxwlvq3egqzu69q20260609143905',
    src: '/menstrual_hygiene_hope_high_2026/supxwlvq3egqzu69q20260609143905.webp',
    alt: 'Close-up of sanitary products distributed during the campaign - School H-34',
    eventId: 'menstrual-hygiene-hope-high-2026',
    eventTitle: 'Menstrual Hygiene Day - Hope High',
    date: 'June 9, 2026',
    year: 2026,
    location: 'Hope High Academy, Zawan',
    aspectRatio: 'landscape'
  },
  {
    id: 'sbj0wm94pm5abhw6o20260609143905',
    src: '/menstrual_hygiene_hope_high_2026/sbj0wm94pm5abhw6o20260609143905.webp',
    alt: 'Students reading educational leaflets on reproductive rights - School H-31',
    eventId: 'menstrual-hygiene-hope-high-2026',
    eventTitle: 'Menstrual Hygiene Day - Hope High',
    date: 'June 9, 2026',
    year: 2026,
    location: 'Hope High Academy, Zawan',
    aspectRatio: 'landscape'
  },
  {
    id: 'sheihbefmgyxiup8920260609143905',
    src: '/menstrual_hygiene_hope_high_2026/sheihbefmgyxiup8920260609143905.webp',
    alt: 'Staff and volunteers posing together - School H-33',
    eventId: 'menstrual-hygiene-hope-high-2026',
    eventTitle: 'Menstrual Hygiene Day - Hope High',
    date: 'June 9, 2026',
    year: 2026,
    location: 'Hope High Academy, Zawan',
    aspectRatio: 'landscape'
  },
  {
    id: 'sj1tfw7oa1pcq78g820260609143906',
    src: '/menstrual_hygiene_hope_high_2026/sj1tfw7oa1pcq78g820260609143906.webp',
    alt: 'Student asking questions during the interactive forum - School H-32',
    eventId: 'menstrual-hygiene-hope-high-2026',
    eventTitle: 'Menstrual Hygiene Day - Hope High',
    date: 'June 9, 2026',
    year: 2026,
    location: 'Hope High Academy, Zawan',
    aspectRatio: 'landscape'
  },
  {
    id: 'snqn8qbflx09mh9nt20260609143906',
    src: '/menstrual_hygiene_hope_high_2026/snqn8qbflx09mh9nt20260609143906.webp',
    alt: 'Demonstrations on hygiene practices by volunteers - School H-36',
    eventId: 'menstrual-hygiene-hope-high-2026',
    eventTitle: 'Menstrual Hygiene Day - Hope High',
    date: 'June 9, 2026',
    year: 2026,
    location: 'Hope High Academy, Zawan',
    aspectRatio: 'landscape'
  },
  {
    id: 'smjwj1fn1clmytwxo20260609143906',
    src: '/menstrual_hygiene_hope_high_2026/smjwj1fn1clmytwxo20260609143906.webp',
    alt: 'Crowd of students holding up their hygiene kits - School H-35',
    eventId: 'menstrual-hygiene-hope-high-2026',
    eventTitle: 'Menstrual Hygiene Day - Hope High',
    date: 'June 9, 2026',
    year: 2026,
    location: 'Hope High Academy, Zawan',
    aspectRatio: 'landscape'
  },
  {
    id: 's8iceks4q3cnb28vn20260609143906',
    src: '/menstrual_hygiene_hope_high_2026/s8iceks4q3cnb28vn20260609143906.webp',
    alt: 'Volunteers smiling at the cameras during seminar setup - School H-39',
    eventId: 'menstrual-hygiene-hope-high-2026',
    eventTitle: 'Menstrual Hygiene Day - Hope High',
    date: 'June 9, 2026',
    year: 2026,
    location: 'Hope High Academy, Zawan',
    aspectRatio: 'landscape'
  },
  {
    id: 'sf9jeadxykpemzc4v20260609143906',
    src: '/menstrual_hygiene_hope_high_2026/sf9jeadxykpemzc4v20260609143906.webp',
    alt: 'One of our medical scientists addressing student health - School H-41',
    eventId: 'menstrual-hygiene-hope-high-2026',
    eventTitle: 'Menstrual Hygiene Day - Hope High',
    date: 'June 9, 2026',
    year: 2026,
    location: 'Hope High Academy, Zawan',
    aspectRatio: 'landscape'
  },
  {
    id: 'sr5uzhx519f3rycns20260609143906',
    src: '/menstrual_hygiene_hope_high_2026/sr5uzhx519f3rycns20260609143906.webp',
    alt: 'Presentation board displaying menstrual cycle timelines - School H-37',
    eventId: 'menstrual-hygiene-hope-high-2026',
    eventTitle: 'Menstrual Hygiene Day - Hope High',
    date: 'June 9, 2026',
    year: 2026,
    location: 'Hope High Academy, Zawan',
    aspectRatio: 'landscape'
  },
  {
    id: 'skb8z8thjmumd12iz20260609143906',
    src: '/menstrual_hygiene_hope_high_2026/skb8z8thjmumd12iz20260609143906.webp',
    alt: 'Group discussion among students regarding boundary setting - School H-38',
    eventId: 'menstrual-hygiene-hope-high-2026',
    eventTitle: 'Menstrual Hygiene Day - Hope High',
    date: 'June 9, 2026',
    year: 2026,
    location: 'Hope High Academy, Zawan',
    aspectRatio: 'landscape'
  },
  {
    id: 'smc98ddlx692lebnv20260609143906',
    src: '/menstrual_hygiene_hope_high_2026/smc98ddlx692lebnv20260609143906.webp',
    alt: 'Classroom filled with students showing support for Padded Girl - School H-40',
    eventId: 'menstrual-hygiene-hope-high-2026',
    eventTitle: 'Menstrual Hygiene Day - Hope High',
    date: 'June 9, 2026',
    year: 2026,
    location: 'Hope High Academy, Zawan',
    aspectRatio: 'landscape'
  },
  {
    id: 'smnca3bq5fdt0o1xz20260609143906',
    src: '/menstrual_hygiene_hope_high_2026/smnca3bq5fdt0o1xz20260609143906.webp',
    alt: 'One of the female student leaders giving feedback - School H-45',
    eventId: 'menstrual-hygiene-hope-high-2026',
    eventTitle: 'Menstrual Hygiene Day - Hope High',
    date: 'June 9, 2026',
    year: 2026,
    location: 'Hope High Academy, Zawan',
    aspectRatio: 'portrait'
  },
  {
    id: 'smgt88i9h7vdh007u20260609143906',
    src: '/menstrual_hygiene_hope_high_2026/smgt88i9h7vdh007u20260609143906.webp',
    alt: 'Close-up of Hope High students smiling - School H-42',
    eventId: 'menstrual-hygiene-hope-high-2026',
    eventTitle: 'Menstrual Hygiene Day - Hope High',
    date: 'June 9, 2026',
    year: 2026,
    location: 'Hope High Academy, Zawan',
    aspectRatio: 'landscape'
  },
  {
    id: 's01cmw81nvstrns0v20260609143906',
    src: '/menstrual_hygiene_hope_high_2026/s01cmw81nvstrns0v20260609143906.webp',
    alt: 'Menstrual Hygiene Day presentation and activities - School H-43',
    eventId: 'menstrual-hygiene-hope-high-2026',
    eventTitle: 'Menstrual Hygiene Day - Hope High',
    date: 'June 9, 2026',
    year: 2026,
    location: 'Hope High Academy, Zawan',
    aspectRatio: 'portrait'
  },
  {
    id: 's1wp3rkr8fx0zwnbs20260609143906',
    src: '/menstrual_hygiene_hope_high_2026/s1wp3rkr8fx0zwnbs20260609143906.webp',
    alt: 'Menstrual Hygiene Day presentation and activities - School H-47',
    eventId: 'menstrual-hygiene-hope-high-2026',
    eventTitle: 'Menstrual Hygiene Day - Hope High',
    date: 'June 9, 2026',
    year: 2026,
    location: 'Hope High Academy, Zawan',
    aspectRatio: 'portrait'
  },
  {
    id: 'ssnpsvk0m7mv96fba20260609143906',
    src: '/menstrual_hygiene_hope_high_2026/ssnpsvk0m7mv96fba20260609143906.webp',
    alt: 'Menstrual Hygiene Day presentation and activities - School H-46',
    eventId: 'menstrual-hygiene-hope-high-2026',
    eventTitle: 'Menstrual Hygiene Day - Hope High',
    date: 'June 9, 2026',
    year: 2026,
    location: 'Hope High Academy, Zawan',
    aspectRatio: 'landscape'
  },
  {
    id: 'sccen4xa32uhm3mrh20260609143906',
    src: '/menstrual_hygiene_hope_high_2026/sccen4xa32uhm3mrh20260609143906.webp',
    alt: 'Menstrual Hygiene Day presentation and activities - School H-48',
    eventId: 'menstrual-hygiene-hope-high-2026',
    eventTitle: 'Menstrual Hygiene Day - Hope High',
    date: 'June 9, 2026',
    year: 2026,
    location: 'Hope High Academy, Zawan',
    aspectRatio: 'portrait'
  },
  {
    id: 'szo2l760i47uitz9g20260609143906',
    src: '/menstrual_hygiene_hope_high_2026/szo2l760i47uitz9g20260609143906.webp',
    alt: 'Menstrual Hygiene Day presentation and activities - School H-44',
    eventId: 'menstrual-hygiene-hope-high-2026',
    eventTitle: 'Menstrual Hygiene Day - Hope High',
    date: 'June 9, 2026',
    year: 2026,
    location: 'Hope High Academy, Zawan',
    aspectRatio: 'portrait'
  },
  {
    id: 'siprj9miuhem47ji720260609143906',
    src: '/menstrual_hygiene_hope_high_2026/siprj9miuhem47ji720260609143906.webp',
    alt: 'Menstrual Hygiene Day presentation and activities - School H-51',
    eventId: 'menstrual-hygiene-hope-high-2026',
    eventTitle: 'Menstrual Hygiene Day - Hope High',
    date: 'June 9, 2026',
    year: 2026,
    location: 'Hope High Academy, Zawan',
    aspectRatio: 'landscape'
  },
  {
    id: 'se6odzqx9den2b6yy20260609143906',
    src: '/menstrual_hygiene_hope_high_2026/se6odzqx9den2b6yy20260609143906.webp',
    alt: 'Menstrual Hygiene Day presentation and activities - School H-49',
    eventId: 'menstrual-hygiene-hope-high-2026',
    eventTitle: 'Menstrual Hygiene Day - Hope High',
    date: 'June 9, 2026',
    year: 2026,
    location: 'Hope High Academy, Zawan',
    aspectRatio: 'landscape'
  },
  {
    id: 's5km7who4phgnhmz620260609143906',
    src: '/menstrual_hygiene_hope_high_2026/s5km7who4phgnhmz620260609143906.webp',
    alt: 'Menstrual Hygiene Day presentation and activities - School H-50',
    eventId: 'menstrual-hygiene-hope-high-2026',
    eventTitle: 'Menstrual Hygiene Day - Hope High',
    date: 'June 9, 2026',
    year: 2026,
    location: 'Hope High Academy, Zawan',
    aspectRatio: 'landscape'
  },
  {
    id: 's6tnmq6kuxn1pynyb20260609143906',
    src: '/menstrual_hygiene_hope_high_2026/s6tnmq6kuxn1pynyb20260609143906.webp',
    alt: 'Menstrual Hygiene Day presentation and activities - School H-52',
    eventId: 'menstrual-hygiene-hope-high-2026',
    eventTitle: 'Menstrual Hygiene Day - Hope High',
    date: 'June 9, 2026',
    year: 2026,
    location: 'Hope High Academy, Zawan',
    aspectRatio: 'landscape'
  },
  {
    id: 's7v2mfmfcl3r2e3wj20260609143906',
    src: '/menstrual_hygiene_hope_high_2026/s7v2mfmfcl3r2e3wj20260609143906.webp',
    alt: 'Menstrual Hygiene Day presentation and activities - School H-53',
    eventId: 'menstrual-hygiene-hope-high-2026',
    eventTitle: 'Menstrual Hygiene Day - Hope High',
    date: 'June 9, 2026',
    year: 2026,
    location: 'Hope High Academy, Zawan',
    aspectRatio: 'landscape'
  },
  {
    id: 'snnvd5hq1v85gig4e20260609143906',
    src: '/menstrual_hygiene_hope_high_2026/snnvd5hq1v85gig4e20260609143906.webp',
    alt: 'Menstrual Hygiene Day presentation and activities - School H-55',
    eventId: 'menstrual-hygiene-hope-high-2026',
    eventTitle: 'Menstrual Hygiene Day - Hope High',
    date: 'June 9, 2026',
    year: 2026,
    location: 'Hope High Academy, Zawan',
    aspectRatio: 'landscape'
  },
  {
    id: 'slur4qrsqmpntqwkm20260609143906',
    src: '/menstrual_hygiene_hope_high_2026/slur4qrsqmpntqwkm20260609143906.webp',
    alt: 'Menstrual Hygiene Day presentation and activities - School H-54',
    eventId: 'menstrual-hygiene-hope-high-2026',
    eventTitle: 'Menstrual Hygiene Day - Hope High',
    date: 'June 9, 2026',
    year: 2026,
    location: 'Hope High Academy, Zawan',
    aspectRatio: 'landscape'
  },
  {
    id: 'shiu51kg1ogu07w3m20260609143906',
    src: '/menstrual_hygiene_hope_high_2026/shiu51kg1ogu07w3m20260609143906.webp',
    alt: 'Menstrual Hygiene Day presentation and activities - School H-57',
    eventId: 'menstrual-hygiene-hope-high-2026',
    eventTitle: 'Menstrual Hygiene Day - Hope High',
    date: 'June 9, 2026',
    year: 2026,
    location: 'Hope High Academy, Zawan',
    aspectRatio: 'landscape'
  },
  {
    id: 'sz8y1wpn9og80tfk620260609143906',
    src: '/menstrual_hygiene_hope_high_2026/sz8y1wpn9og80tfk620260609143906.webp',
    alt: 'Menstrual Hygiene Day presentation and activities - School H-56',
    eventId: 'menstrual-hygiene-hope-high-2026',
    eventTitle: 'Menstrual Hygiene Day - Hope High',
    date: 'June 9, 2026',
    year: 2026,
    location: 'Hope High Academy, Zawan',
    aspectRatio: 'landscape'
  },
  {
    id: 'sn1czkzlf5lb107wr20260609143907',
    src: '/menstrual_hygiene_hope_high_2026/sn1czkzlf5lb107wr20260609143907.webp',
    alt: 'Menstrual Hygiene Day presentation and activities - School H-58',
    eventId: 'menstrual-hygiene-hope-high-2026',
    eventTitle: 'Menstrual Hygiene Day - Hope High',
    date: 'June 9, 2026',
    year: 2026,
    location: 'Hope High Academy, Zawan',
    aspectRatio: 'landscape'
  },
  {
    id: 'slr3agj8ikvohd5h920260609143907',
    src: '/menstrual_hygiene_hope_high_2026/slr3agj8ikvohd5h920260609143907.webp',
    alt: 'Menstrual Hygiene Day presentation and activities - School H-59',
    eventId: 'menstrual-hygiene-hope-high-2026',
    eventTitle: 'Menstrual Hygiene Day - Hope High',
    date: 'June 9, 2026',
    year: 2026,
    location: 'Hope High Academy, Zawan',
    aspectRatio: 'landscape'
  },
  {
    id: 's58lgn3bl32p6j54d20260609143907',
    src: '/menstrual_hygiene_hope_high_2026/s58lgn3bl32p6j54d20260609143907.webp',
    alt: 'Menstrual Hygiene Day presentation and activities - School H-60',
    eventId: 'menstrual-hygiene-hope-high-2026',
    eventTitle: 'Menstrual Hygiene Day - Hope High',
    date: 'June 9, 2026',
    year: 2026,
    location: 'Hope High Academy, Zawan',
    aspectRatio: 'landscape'
  },
  {
    id: 's6i0ivaxxds7xuzpn20260609143907',
    src: '/menstrual_hygiene_hope_high_2026/s6i0ivaxxds7xuzpn20260609143907.webp',
    alt: 'Menstrual Hygiene Day presentation and activities - School H-61',
    eventId: 'menstrual-hygiene-hope-high-2026',
    eventTitle: 'Menstrual Hygiene Day - Hope High',
    date: 'June 9, 2026',
    year: 2026,
    location: 'Hope High Academy, Zawan',
    aspectRatio: 'landscape'
  },
  {
    id: 's36rsw6gahoxniuex20260609143907',
    src: '/menstrual_hygiene_hope_high_2026/s36rsw6gahoxniuex20260609143907.webp',
    alt: 'Menstrual Hygiene Day presentation and activities - School H-62',
    eventId: 'menstrual-hygiene-hope-high-2026',
    eventTitle: 'Menstrual Hygiene Day - Hope High',
    date: 'June 9, 2026',
    year: 2026,
    location: 'Hope High Academy, Zawan',
    aspectRatio: 'landscape'
  },
  {
    id: 'se78psjlz6nl08d3e20260609143907',
    src: '/menstrual_hygiene_hope_high_2026/se78psjlz6nl08d3e20260609143907.webp',
    alt: 'Menstrual Hygiene Day presentation and activities - School H-63',
    eventId: 'menstrual-hygiene-hope-high-2026',
    eventTitle: 'Menstrual Hygiene Day - Hope High',
    date: 'June 9, 2026',
    year: 2026,
    location: 'Hope High Academy, Zawan',
    aspectRatio: 'landscape'
  },
  {
    id: 'skqaxpo6rc82r70y820260609143907',
    src: '/menstrual_hygiene_hope_high_2026/skqaxpo6rc82r70y820260609143907.webp',
    alt: 'Menstrual Hygiene Day presentation and activities - School H-64',
    eventId: 'menstrual-hygiene-hope-high-2026',
    eventTitle: 'Menstrual Hygiene Day - Hope High',
    date: 'June 9, 2026',
    year: 2026,
    location: 'Hope High Academy, Zawan',
    aspectRatio: 'landscape'
  },
  {
    id: 'sw3e5nekgezjhne7q20260609143907',
    src: '/menstrual_hygiene_hope_high_2026/sw3e5nekgezjhne7q20260609143907.webp',
    alt: 'Menstrual Hygiene Day presentation and activities - School H-65',
    eventId: 'menstrual-hygiene-hope-high-2026',
    eventTitle: 'Menstrual Hygiene Day - Hope High',
    date: 'June 9, 2026',
    year: 2026,
    location: 'Hope High Academy, Zawan',
    aspectRatio: 'landscape'
  },
  {
    id: 'svu1xhrxc23695q6n20260609143907',
    src: '/menstrual_hygiene_hope_high_2026/svu1xhrxc23695q6n20260609143907.webp',
    alt: 'Menstrual Hygiene Day presentation and activities - School H-70',
    eventId: 'menstrual-hygiene-hope-high-2026',
    eventTitle: 'Menstrual Hygiene Day - Hope High',
    date: 'June 9, 2026',
    year: 2026,
    location: 'Hope High Academy, Zawan',
    aspectRatio: 'portrait'
  },
  {
    id: 'shjcffoav1nu8cyyf20260609143907',
    src: '/menstrual_hygiene_hope_high_2026/shjcffoav1nu8cyyf20260609143907.webp',
    alt: 'Menstrual Hygiene Day presentation and activities - School H-69',
    eventId: 'menstrual-hygiene-hope-high-2026',
    eventTitle: 'Menstrual Hygiene Day - Hope High',
    date: 'June 9, 2026',
    year: 2026,
    location: 'Hope High Academy, Zawan',
    aspectRatio: 'landscape'
  },
  {
    id: 'svoay9y3s44php3wc20260609143907',
    src: '/menstrual_hygiene_hope_high_2026/svoay9y3s44php3wc20260609143907.webp',
    alt: 'Menstrual Hygiene Day presentation and activities - School H-67',
    eventId: 'menstrual-hygiene-hope-high-2026',
    eventTitle: 'Menstrual Hygiene Day - Hope High',
    date: 'June 9, 2026',
    year: 2026,
    location: 'Hope High Academy, Zawan',
    aspectRatio: 'landscape'
  },
  {
    id: 'si5t22r72vflnx5c820260609143907',
    src: '/menstrual_hygiene_hope_high_2026/si5t22r72vflnx5c820260609143907.webp',
    alt: 'Menstrual Hygiene Day presentation and activities - School H-68',
    eventId: 'menstrual-hygiene-hope-high-2026',
    eventTitle: 'Menstrual Hygiene Day - Hope High',
    date: 'June 9, 2026',
    year: 2026,
    location: 'Hope High Academy, Zawan',
    aspectRatio: 'landscape'
  },
  {
    id: 'syvl50adj49ojoqxx20260609143907',
    src: '/menstrual_hygiene_hope_high_2026/syvl50adj49ojoqxx20260609143907.webp',
    alt: 'Menstrual Hygiene Day presentation and activities - School H-66',
    eventId: 'menstrual-hygiene-hope-high-2026',
    eventTitle: 'Menstrual Hygiene Day - Hope High',
    date: 'June 9, 2026',
    year: 2026,
    location: 'Hope High Academy, Zawan',
    aspectRatio: 'landscape'
  },
  {
    id: 'sz51yqtpu9s0bgm3g20260609143907',
    src: '/menstrual_hygiene_hope_high_2026/sz51yqtpu9s0bgm3g20260609143907.webp',
    alt: 'Menstrual Hygiene Day presentation and activities - School H-77',
    eventId: 'menstrual-hygiene-hope-high-2026',
    eventTitle: 'Menstrual Hygiene Day - Hope High',
    date: 'June 9, 2026',
    year: 2026,
    location: 'Hope High Academy, Zawan',
    aspectRatio: 'landscape'
  },
  {
    id: 'sq0slmoj3q4pmiepm20260609143907',
    src: '/menstrual_hygiene_hope_high_2026/sq0slmoj3q4pmiepm20260609143907.webp',
    alt: 'Menstrual Hygiene Day presentation and activities - School H-73',
    eventId: 'menstrual-hygiene-hope-high-2026',
    eventTitle: 'Menstrual Hygiene Day - Hope High',
    date: 'June 9, 2026',
    year: 2026,
    location: 'Hope High Academy, Zawan',
    aspectRatio: 'landscape'
  },
  {
    id: 'sopwhtxfjo7taocwf20260609143907',
    src: '/menstrual_hygiene_hope_high_2026/sopwhtxfjo7taocwf20260609143907.webp',
    alt: 'Menstrual Hygiene Day presentation and activities - School H-71',
    eventId: 'menstrual-hygiene-hope-high-2026',
    eventTitle: 'Menstrual Hygiene Day - Hope High',
    date: 'June 9, 2026',
    year: 2026,
    location: 'Hope High Academy, Zawan',
    aspectRatio: 'landscape'
  },
  {
    id: 's4jaau38gwq6im69220260609143907',
    src: '/menstrual_hygiene_hope_high_2026/s4jaau38gwq6im69220260609143907.webp',
    alt: 'Menstrual Hygiene Day presentation and activities - School H-75',
    eventId: 'menstrual-hygiene-hope-high-2026',
    eventTitle: 'Menstrual Hygiene Day - Hope High',
    date: 'June 9, 2026',
    year: 2026,
    location: 'Hope High Academy, Zawan',
    aspectRatio: 'landscape'
  },
  {
    id: 'sajn9d3fifoyj8f7e20260609143907',
    src: '/menstrual_hygiene_hope_high_2026/sajn9d3fifoyj8f7e20260609143907.webp',
    alt: 'Menstrual Hygiene Day presentation and activities - School H-74',
    eventId: 'menstrual-hygiene-hope-high-2026',
    eventTitle: 'Menstrual Hygiene Day - Hope High',
    date: 'June 9, 2026',
    year: 2026,
    location: 'Hope High Academy, Zawan',
    aspectRatio: 'landscape'
  },
  {
    id: 'syjnuf9t2jp2zcjwc20260609143907',
    src: '/menstrual_hygiene_hope_high_2026/syjnuf9t2jp2zcjwc20260609143907.webp',
    alt: 'Menstrual Hygiene Day presentation and activities - School H-76',
    eventId: 'menstrual-hygiene-hope-high-2026',
    eventTitle: 'Menstrual Hygiene Day - Hope High',
    date: 'June 9, 2026',
    year: 2026,
    location: 'Hope High Academy, Zawan',
    aspectRatio: 'landscape'
  },
  {
    id: 'ss6wkpkjun5gs9ud620260609143907',
    src: '/menstrual_hygiene_hope_high_2026/ss6wkpkjun5gs9ud620260609143907.webp',
    alt: 'Menstrual Hygiene Day presentation and activities - School H-82',
    eventId: 'menstrual-hygiene-hope-high-2026',
    eventTitle: 'Menstrual Hygiene Day - Hope High',
    date: 'June 9, 2026',
    year: 2026,
    location: 'Hope High Academy, Zawan',
    aspectRatio: 'landscape'
  },
  {
    id: 'sqvcq7fhjgzjfapnf20260609143907',
    src: '/menstrual_hygiene_hope_high_2026/sqvcq7fhjgzjfapnf20260609143907.webp',
    alt: 'Menstrual Hygiene Day presentation and activities - School H-72',
    eventId: 'menstrual-hygiene-hope-high-2026',
    eventTitle: 'Menstrual Hygiene Day - Hope High',
    date: 'June 9, 2026',
    year: 2026,
    location: 'Hope High Academy, Zawan',
    aspectRatio: 'landscape'
  },
  {
    id: 'scewwmv3q1w6gwvdd20260609143907',
    src: '/menstrual_hygiene_hope_high_2026/scewwmv3q1w6gwvdd20260609143907.webp',
    alt: 'Menstrual Hygiene Day presentation and activities - School H-78',
    eventId: 'menstrual-hygiene-hope-high-2026',
    eventTitle: 'Menstrual Hygiene Day - Hope High',
    date: 'June 9, 2026',
    year: 2026,
    location: 'Hope High Academy, Zawan',
    aspectRatio: 'landscape'
  },
  {
    id: 's7rf1qq18vmwq7g1z20260609143907',
    src: '/menstrual_hygiene_hope_high_2026/s7rf1qq18vmwq7g1z20260609143907.webp',
    alt: 'Menstrual Hygiene Day presentation and activities - School H-81',
    eventId: 'menstrual-hygiene-hope-high-2026',
    eventTitle: 'Menstrual Hygiene Day - Hope High',
    date: 'June 9, 2026',
    year: 2026,
    location: 'Hope High Academy, Zawan',
    aspectRatio: 'landscape'
  },
  {
    id: 'sd0izom80wu37rl1y20260609143907',
    src: '/menstrual_hygiene_hope_high_2026/sd0izom80wu37rl1y20260609143907.webp',
    alt: 'Menstrual Hygiene Day presentation and activities - School H-79',
    eventId: 'menstrual-hygiene-hope-high-2026',
    eventTitle: 'Menstrual Hygiene Day - Hope High',
    date: 'June 9, 2026',
    year: 2026,
    location: 'Hope High Academy, Zawan',
    aspectRatio: 'landscape'
  },
  {
    id: 's9ift57lx897z6xk020260609143907',
    src: '/menstrual_hygiene_hope_high_2026/s9ift57lx897z6xk020260609143907.webp',
    alt: 'Menstrual Hygiene Day presentation and activities - School H-80',
    eventId: 'menstrual-hygiene-hope-high-2026',
    eventTitle: 'Menstrual Hygiene Day - Hope High',
    date: 'June 9, 2026',
    year: 2026,
    location: 'Hope High Academy, Zawan',
    aspectRatio: 'landscape'
  },
  {
    id: 'sy63vlp7lzbom9l9g20260609143908',
    src: '/menstrual_hygiene_hope_high_2026/sy63vlp7lzbom9l9g20260609143908.webp',
    alt: 'Menstrual Hygiene Day presentation and activities - School H',
    eventId: 'menstrual-hygiene-hope-high-2026',
    eventTitle: 'Menstrual Hygiene Day - Hope High',
    date: 'June 9, 2026',
    year: 2026,
    location: 'Hope High Academy, Zawan',
    aspectRatio: 'landscape'
  },
  {
    id: 'smfr2e79qsbkectmy20260609143908',
    src: '/menstrual_hygiene_hope_high_2026/smfr2e79qsbkectmy20260609143908.webp',
    alt: 'Menstrual Hygiene Day presentation and activities - School H-7',
    eventId: 'menstrual-hygiene-hope-high-2026',
    eventTitle: 'Menstrual Hygiene Day - Hope High',
    date: 'June 9, 2026',
    year: 2026,
    location: 'Hope High Academy, Zawan',
    aspectRatio: 'landscape'
  },
  {
    id: 'sjp0rgx4svcsiuvh520260609143908',
    src: '/menstrual_hygiene_hope_high_2026/sjp0rgx4svcsiuvh520260609143908.webp',
    alt: 'Menstrual Hygiene Day presentation and activities - School H-2',
    eventId: 'menstrual-hygiene-hope-high-2026',
    eventTitle: 'Menstrual Hygiene Day - Hope High',
    date: 'June 9, 2026',
    year: 2026,
    location: 'Hope High Academy, Zawan',
    aspectRatio: 'landscape'
  },
  {
    id: 's7op077er28lzovdw20260609143908',
    src: '/menstrual_hygiene_hope_high_2026/s7op077er28lzovdw20260609143908.webp',
    alt: 'Menstrual Hygiene Day presentation and activities - School H-5',
    eventId: 'menstrual-hygiene-hope-high-2026',
    eventTitle: 'Menstrual Hygiene Day - Hope High',
    date: 'June 9, 2026',
    year: 2026,
    location: 'Hope High Academy, Zawan',
    aspectRatio: 'landscape'
  },
  {
    id: 'sa7b223ax1hi6296p20260609143908',
    src: '/menstrual_hygiene_hope_high_2026/sa7b223ax1hi6296p20260609143908.webp',
    alt: 'Menstrual Hygiene Day presentation and activities - School H-6',
    eventId: 'menstrual-hygiene-hope-high-2026',
    eventTitle: 'Menstrual Hygiene Day - Hope High',
    date: 'June 9, 2026',
    year: 2026,
    location: 'Hope High Academy, Zawan',
    aspectRatio: 'landscape'
  },
  {
    id: 's9xwmtlq1o6shgxio20260609143908',
    src: '/menstrual_hygiene_hope_high_2026/s9xwmtlq1o6shgxio20260609143908.webp',
    alt: 'Menstrual Hygiene Day presentation and activities - School H-3',
    eventId: 'menstrual-hygiene-hope-high-2026',
    eventTitle: 'Menstrual Hygiene Day - Hope High',
    date: 'June 9, 2026',
    year: 2026,
    location: 'Hope High Academy, Zawan',
    aspectRatio: 'landscape'
  },
  {
    id: 'spz0rxgspyevenbho20260609143908',
    src: '/menstrual_hygiene_hope_high_2026/spz0rxgspyevenbho20260609143908.webp',
    alt: 'Menstrual Hygiene Day presentation and activities - School H-4',
    eventId: 'menstrual-hygiene-hope-high-2026',
    eventTitle: 'Menstrual Hygiene Day - Hope High',
    date: 'June 9, 2026',
    year: 2026,
    location: 'Hope High Academy, Zawan',
    aspectRatio: 'landscape'
  },
  {
    id: 'so1yltn36h58oysn220260609143908',
    src: '/menstrual_hygiene_hope_high_2026/so1yltn36h58oysn220260609143908.webp',
    alt: 'Menstrual Hygiene Day presentation and activities - School H-10',
    eventId: 'menstrual-hygiene-hope-high-2026',
    eventTitle: 'Menstrual Hygiene Day - Hope High',
    date: 'June 9, 2026',
    year: 2026,
    location: 'Hope High Academy, Zawan',
    aspectRatio: 'landscape'
  },
  {
    id: 's7urzjgdazgp92j6r20260609143908',
    src: '/menstrual_hygiene_hope_high_2026/s7urzjgdazgp92j6r20260609143908.webp',
    alt: 'Menstrual Hygiene Day presentation and activities - School H-8',
    eventId: 'menstrual-hygiene-hope-high-2026',
    eventTitle: 'Menstrual Hygiene Day - Hope High',
    date: 'June 9, 2026',
    year: 2026,
    location: 'Hope High Academy, Zawan',
    aspectRatio: 'landscape'
  },
  {
    id: 's228c1yspeentaigg20260609143908',
    src: '/menstrual_hygiene_hope_high_2026/s228c1yspeentaigg20260609143908.webp',
    alt: 'Menstrual Hygiene Day presentation and activities - School H-11',
    eventId: 'menstrual-hygiene-hope-high-2026',
    eventTitle: 'Menstrual Hygiene Day - Hope High',
    date: 'June 9, 2026',
    year: 2026,
    location: 'Hope High Academy, Zawan',
    aspectRatio: 'landscape'
  },
  {
    id: 's1aqhybkflrva52uc20260609143908',
    src: '/menstrual_hygiene_hope_high_2026/s1aqhybkflrva52uc20260609143908.webp',
    alt: 'Menstrual Hygiene Day presentation and activities - School H-12',
    eventId: 'menstrual-hygiene-hope-high-2026',
    eventTitle: 'Menstrual Hygiene Day - Hope High',
    date: 'June 9, 2026',
    year: 2026,
    location: 'Hope High Academy, Zawan',
    aspectRatio: 'landscape'
  },
  {
    id: 'sjeby8s70k8egk80o20260609143908',
    src: '/menstrual_hygiene_hope_high_2026/sjeby8s70k8egk80o20260609143908.webp',
    alt: 'Menstrual Hygiene Day presentation and activities - School H-9',
    eventId: 'menstrual-hygiene-hope-high-2026',
    eventTitle: 'Menstrual Hygiene Day - Hope High',
    date: 'June 9, 2026',
    year: 2026,
    location: 'Hope High Academy, Zawan',
    aspectRatio: 'landscape'
  },
  {
    id: 'sa6qej99hyx4aggd520260609143908',
    src: '/menstrual_hygiene_hope_high_2026/sa6qej99hyx4aggd520260609143908.webp',
    alt: 'Menstrual Hygiene Day presentation and activities - School H-13',
    eventId: 'menstrual-hygiene-hope-high-2026',
    eventTitle: 'Menstrual Hygiene Day - Hope High',
    date: 'June 9, 2026',
    year: 2026,
    location: 'Hope High Academy, Zawan',
    aspectRatio: 'landscape'
  },
  {
    id: 'sr19vcuw35rc2zjiw20260609143908',
    src: '/menstrual_hygiene_hope_high_2026/sr19vcuw35rc2zjiw20260609143908.webp',
    alt: 'Menstrual Hygiene Day presentation and activities - School H-15',
    eventId: 'menstrual-hygiene-hope-high-2026',
    eventTitle: 'Menstrual Hygiene Day - Hope High',
    date: 'June 9, 2026',
    year: 2026,
    location: 'Hope High Academy, Zawan',
    aspectRatio: 'landscape'
  },
  {
    id: 'szub7s4ckiqvbptsw20260609143908',
    src: '/menstrual_hygiene_hope_high_2026/szub7s4ckiqvbptsw20260609143908.webp',
    alt: 'Menstrual Hygiene Day presentation and activities - School H-14',
    eventId: 'menstrual-hygiene-hope-high-2026',
    eventTitle: 'Menstrual Hygiene Day - Hope High',
    date: 'June 9, 2026',
    year: 2026,
    location: 'Hope High Academy, Zawan',
    aspectRatio: 'landscape'
  },
  {
    id: 'sfj1whuacnwq9njzp20260609143908',
    src: '/menstrual_hygiene_hope_high_2026/sfj1whuacnwq9njzp20260609143908.webp',
    alt: 'Menstrual Hygiene Day presentation and activities - School H-20',
    eventId: 'menstrual-hygiene-hope-high-2026',
    eventTitle: 'Menstrual Hygiene Day - Hope High',
    date: 'June 9, 2026',
    year: 2026,
    location: 'Hope High Academy, Zawan',
    aspectRatio: 'landscape'
  },
  {
    id: 'sgz94h2dqmmxqv7xp20260609143908',
    src: '/menstrual_hygiene_hope_high_2026/sgz94h2dqmmxqv7xp20260609143908.webp',
    alt: 'Menstrual Hygiene Day presentation and activities - School H-16',
    eventId: 'menstrual-hygiene-hope-high-2026',
    eventTitle: 'Menstrual Hygiene Day - Hope High',
    date: 'June 9, 2026',
    year: 2026,
    location: 'Hope High Academy, Zawan',
    aspectRatio: 'landscape'
  },
  {
    id: 's1uphrt5ptf66ltef20260609143908',
    src: '/menstrual_hygiene_hope_high_2026/s1uphrt5ptf66ltef20260609143908.webp',
    alt: 'Menstrual Hygiene Day presentation and activities - School H-17',
    eventId: 'menstrual-hygiene-hope-high-2026',
    eventTitle: 'Menstrual Hygiene Day - Hope High',
    date: 'June 9, 2026',
    year: 2026,
    location: 'Hope High Academy, Zawan',
    aspectRatio: 'landscape'
  },
  {
    id: 'smginjotzl29pam4620260609143908',
    src: '/menstrual_hygiene_hope_high_2026/smginjotzl29pam4620260609143908.webp',
    alt: 'Menstrual Hygiene Day presentation and activities - School H-19',
    eventId: 'menstrual-hygiene-hope-high-2026',
    eventTitle: 'Menstrual Hygiene Day - Hope High',
    date: 'June 9, 2026',
    year: 2026,
    location: 'Hope High Academy, Zawan',
    aspectRatio: 'landscape'
  },
  {
    id: 'sebu9z3seonw8ougk20260609143908',
    src: '/menstrual_hygiene_hope_high_2026/sebu9z3seonw8ougk20260609143908.webp',
    alt: 'Menstrual Hygiene Day presentation and activities - School H-18',
    eventId: 'menstrual-hygiene-hope-high-2026',
    eventTitle: 'Menstrual Hygiene Day - Hope High',
    date: 'June 9, 2026',
    year: 2026,
    location: 'Hope High Academy, Zawan',
    aspectRatio: 'landscape'
  },
  {
    id: 'sjamuzeqpkregviby20260609143908',
    src: '/menstrual_hygiene_hope_high_2026/sjamuzeqpkregviby20260609143908.webp',
    alt: 'Menstrual Hygiene Day presentation and activities - School H-23',
    eventId: 'menstrual-hygiene-hope-high-2026',
    eventTitle: 'Menstrual Hygiene Day - Hope High',
    date: 'June 9, 2026',
    year: 2026,
    location: 'Hope High Academy, Zawan',
    aspectRatio: 'landscape'
  },
  {
    id: 'stbvhsizrj0xfeh5a20260609143908',
    src: '/menstrual_hygiene_hope_high_2026/stbvhsizrj0xfeh5a20260609143908.webp',
    alt: 'Menstrual Hygiene Day presentation and activities - School H-21',
    eventId: 'menstrual-hygiene-hope-high-2026',
    eventTitle: 'Menstrual Hygiene Day - Hope High',
    date: 'June 9, 2026',
    year: 2026,
    location: 'Hope High Academy, Zawan',
    aspectRatio: 'landscape'
  },
  {
    id: 's86kdm0sv97gi6omi20260609143908',
    src: '/menstrual_hygiene_hope_high_2026/s86kdm0sv97gi6omi20260609143908.webp',
    alt: 'Menstrual Hygiene Day presentation and activities - School H-22',
    eventId: 'menstrual-hygiene-hope-high-2026',
    eventTitle: 'Menstrual Hygiene Day - Hope High',
    date: 'June 9, 2026',
    year: 2026,
    location: 'Hope High Academy, Zawan',
    aspectRatio: 'landscape'
  },
  // 1.1 Google Drive Additional Images (Official Partnership with TCNN - May 2026)
  {
    id: 'gd-1',
    src: 'https://drive.google.com/u/0/drive-usercontent/16f7MBHmOFDQy0zmem-xvDqZ29jPG0rrz=w400-h380-p-k-rw-v1-nu-iv1?auditContext=thumbnail',
    alt: 'Official partnership workshop session at TCNN',
    eventId: 'tcnn-partnership-2026',
    eventTitle: 'Official Partnership with TCNN',
    date: 'May 2026',
    year: 2026,
    location: 'TCNN Bukuru, Plateau State',
    aspectRatio: 'landscape'
  },
  {
    id: 'gd-2',
    src: 'https://drive.google.com/u/0/drive-usercontent/1fZX2r5D-PhoMSZ8B8ZYuaog-nEy_qCyf=w400-h380-p-k-rw-v1-nu-iv1?auditContext=thumbnail',
    alt: 'Interactive discussion groups regarding joint advocacy',
    eventId: 'tcnn-partnership-2026',
    eventTitle: 'Official Partnership with TCNN',
    date: 'May 2026',
    year: 2026,
    location: 'TCNN Bukuru, Plateau State',
    aspectRatio: 'landscape'
  },
  {
    id: 'gd-3',
    src: 'https://drive.google.com/u/0/drive-usercontent/1QkkThGJ0eltasg18GgRwxFgd5XAW90Zy=w400-h380-p-k-rw-v1-nu-iv1?auditContext=thumbnail',
    alt: 'Partnership launch and student development seminar',
    eventId: 'tcnn-partnership-2026',
    eventTitle: 'Official Partnership with TCNN',
    date: 'May 2026',
    year: 2026,
    location: 'TCNN Bukuru, Plateau State',
    aspectRatio: 'landscape'
  },
  {
    id: 'gd-4',
    src: 'https://drive.google.com/u/0/drive-usercontent/1BfqCMcncdPjrHVgOYzqgRgjS6JKoE1g0=w400-h380-p-k-rw-v1-nu-iv1?auditContext=thumbnail',
    alt: 'Collaborative development classes and educational resources',
    eventId: 'tcnn-partnership-2026',
    eventTitle: 'Official Partnership with TCNN',
    date: 'May 2026',
    year: 2026,
    location: 'TCNN Bukuru, Plateau State',
    aspectRatio: 'landscape'
  },
  {
    id: 'gd-5',
    src: 'https://drive.google.com/u/0/drive-usercontent/1WVaNWS_uJsDVneggosbG1a1gXefk-c3_=w400-h380-p-k-rw-v1-nu-iv1?auditContext=thumbnail',
    alt: 'Joint safety initiative launches at TCNN Bukuru',
    eventId: 'tcnn-partnership-2026',
    eventTitle: 'Official Partnership with TCNN',
    date: 'May 2026',
    year: 2026,
    location: 'TCNN Bukuru, Plateau State',
    aspectRatio: 'landscape'
  },
  {
    id: 'gd-6',
    src: 'https://drive.google.com/u/0/drive-usercontent/1ZxY63aPA4xCyrgm70IMJW7uucDBU8jxP=w400-h380-p-k-rw-v1-nu-iv1?auditContext=thumbnail',
    alt: 'Leaders exchanging ideas on girl child mentorship',
    eventId: 'tcnn-partnership-2026',
    eventTitle: 'Official Partnership with TCNN',
    date: 'May 2026',
    year: 2026,
    location: 'TCNN Bukuru, Plateau State',
    aspectRatio: 'landscape'
  },
  {
    id: 'gd-7',
    src: 'https://drive.google.com/u/0/drive-usercontent/1eHiQLSln6vyTa6HosFpb8niPPCMc1_ZP=w400-h380-p-k-rw-v1-nu-iv1?auditContext=thumbnail',
    alt: 'Mentorship network discussions and planning sessions',
    eventId: 'tcnn-partnership-2026',
    eventTitle: 'Official Partnership with TCNN',
    date: 'May 2026',
    year: 2026,
    location: 'TCNN Bukuru, Plateau State',
    aspectRatio: 'landscape'
  },
  {
    id: 'gd-8',
    src: 'https://drive.google.com/u/0/drive-usercontent/1qd0CrOvoA5qkimh7zAFZzZufLe_jyqu0=w400-h380-p-k-rw-v1-nu-iv1?auditContext=thumbnail',
    alt: 'Resource setups and support structures at TCNN campus',
    eventId: 'tcnn-partnership-2026',
    eventTitle: 'Official Partnership with TCNN',
    date: 'May 2026',
    year: 2026,
    location: 'TCNN Bukuru, Plateau State',
    aspectRatio: 'landscape'
  },
  {
    id: 'gd-9',
    src: 'https://drive.google.com/u/0/drive-usercontent/1NsjK1tItxGdlmq6oFAlI1Gzf4XnMJGYY=w400-h380-p-k-rw-v1-nu-iv1?auditContext=thumbnail',
    alt: 'Interactive forum with youth leaders on safety networks',
    eventId: 'tcnn-partnership-2026',
    eventTitle: 'Official Partnership with TCNN',
    date: 'May 2026',
    year: 2026,
    location: 'TCNN Bukuru, Plateau State',
    aspectRatio: 'landscape'
  },
  {
    id: 'gd-10',
    src: 'https://drive.google.com/u/0/drive-usercontent/1xnvYM8MMpXV59uW7ae4wvOEwLCZ55pRi=w400-h380-p-k-rw-v1-nu-iv1?auditContext=thumbnail',
    alt: 'Mentors leading discussion circles at TCNN',
    eventId: 'tcnn-partnership-2026',
    eventTitle: 'Official Partnership with TCNN',
    date: 'May 2026',
    year: 2026,
    location: 'TCNN Bukuru, Plateau State',
    aspectRatio: 'landscape'
  },
  {
    id: 'gd-11',
    src: 'https://drive.google.com/u/0/drive-usercontent/1ID_Xf1stuQN_zdAZ0n4lAvQPOKIF2xgW=w400-h380-p-k-rw-v1-nu-iv1?auditContext=thumbnail',
    alt: 'Advocacy literature distribution inside the campus',
    eventId: 'tcnn-partnership-2026',
    eventTitle: 'Official Partnership with TCNN',
    date: 'May 2026',
    year: 2026,
    location: 'TCNN Bukuru, Plateau State',
    aspectRatio: 'landscape'
  },
  {
    id: 'gd-12',
    src: 'https://drive.google.com/u/0/drive-usercontent/1_U7h7Ba3uzUgw43wQC13iBRQwq0XLKPS=w400-h380-p-k-rw-v1-nu-iv1?auditContext=thumbnail',
    alt: 'Student and leader collaboration session on reproductive rights',
    eventId: 'tcnn-partnership-2026',
    eventTitle: 'Official Partnership with TCNN',
    date: 'May 2026',
    year: 2026,
    location: 'TCNN Bukuru, Plateau State',
    aspectRatio: 'landscape'
  },
  {
    id: 'gd-13',
    src: 'https://drive.google.com/u/0/drive-usercontent/1safSIJzK2Wz6E-oZR4JQty36fLdPnaLp=w400-h380-p-k-rw-v1-nu-iv1?auditContext=thumbnail',
    alt: 'Joint session detailing mental health strategies and outreach',
    eventId: 'tcnn-partnership-2026',
    eventTitle: 'Official Partnership with TCNN',
    date: 'May 2026',
    year: 2026,
    location: 'TCNN Bukuru, Plateau State',
    aspectRatio: 'landscape'
  },
  {
    id: 'gd-14',
    src: 'https://drive.google.com/u/0/drive-usercontent/189-ftpduCieYImD0QtyVQXIDxa7wXM9M=w400-h380-p-k-rw-v1-nu-iv1?auditContext=thumbnail',
    alt: 'Attendees gather after the joint partnership seminar',
    eventId: 'tcnn-partnership-2026',
    eventTitle: 'Official Partnership with TCNN',
    date: 'May 2026',
    year: 2026,
    location: 'TCNN Bukuru, Plateau State',
    aspectRatio: 'landscape'
  },
  {
    id: 'gd-15',
    src: 'https://drive.google.com/u/0/drive-usercontent/1r21SGUoDVdlVaI1XmDtQDfDtn2GIf24u=w400-h380-p-k-rw-v1-nu-iv1?auditContext=thumbnail',
    alt: 'Collaboration workshop slides and presenter address',
    eventId: 'tcnn-partnership-2026',
    eventTitle: 'Official Partnership with TCNN',
    date: 'May 2026',
    year: 2026,
    location: 'TCNN Bukuru, Plateau State',
    aspectRatio: 'landscape'
  },
  {
    id: 'gd-16',
    src: 'https://drive.google.com/u/0/drive-usercontent/1qK4JPm7PzkPo8NqkAhy17g93eAt-H46G=w400-h380-p-k-rw-v1-nu-iv1?auditContext=thumbnail',
    alt: 'Counseling and mentorship launch programs',
    eventId: 'tcnn-partnership-2026',
    eventTitle: 'Official Partnership with TCNN',
    date: 'May 2026',
    year: 2026,
    location: 'TCNN Bukuru, Plateau State',
    aspectRatio: 'landscape'
  },
  {
    id: 'gd-17',
    src: 'https://drive.google.com/u/0/drive-usercontent/1a-9K7H4L2NgFzXq56P1_WXVKryOJiuLT=w400-h380-p-k-rw-v1-nu-iv1?auditContext=thumbnail',
    alt: 'Roleplaying boundaries and consent sessions',
    eventId: 'tcnn-partnership-2026',
    eventTitle: 'Official Partnership with TCNN',
    date: 'May 2026',
    year: 2026,
    location: 'TCNN Bukuru, Plateau State',
    aspectRatio: 'landscape'
  },
  {
    id: 'gd-18',
    src: 'https://drive.google.com/u/0/drive-usercontent/1GB5mB5QkzsZQ0HxK_BUh5kbo2pscopYk=w400-h380-p-k-rw-v1-nu-iv1?auditContext=thumbnail',
    alt: 'Panel discussion on youth abuse prevention guidelines',
    eventId: 'tcnn-partnership-2026',
    eventTitle: 'Official Partnership with TCNN',
    date: 'May 2026',
    year: 2026,
    location: 'TCNN Bukuru, Plateau State',
    aspectRatio: 'landscape'
  },
  {
    id: 'gd-19',
    src: 'https://drive.google.com/u/0/drive-usercontent/10t8BSxL6bcJrv3xp9LvlRx6yiXJvERj8=w400-h380-p-k-rw-v1-nu-iv1?auditContext=thumbnail',
    alt: 'TCNN students posing with advocacy banners',
    eventId: 'tcnn-partnership-2026',
    eventTitle: 'Official Partnership with TCNN',
    date: 'May 2026',
    year: 2026,
    location: 'TCNN Bukuru, Plateau State',
    aspectRatio: 'landscape'
  },
  {
    id: 'gd-20',
    src: 'https://drive.google.com/u/0/drive-usercontent/1vQI0dMayD8mnwMBTn0GlPjrIha09ayW1=w400-h380-p-k-rw-v1-nu-iv1?auditContext=thumbnail',
    alt: 'TCNN Bukuru collaboration event group view',
    eventId: 'tcnn-partnership-2026',
    eventTitle: 'Official Partnership with TCNN',
    date: 'May 2026',
    year: 2026,
    location: 'TCNN Bukuru, Plateau State',
    aspectRatio: 'landscape'
  },
  {
    id: 'gd-21',
    src: 'https://drive.google.com/u/0/drive-usercontent/1vYuH4POPIckXaC7IfdfBwhW8c9RkIImk=w400-h380-p-k-rw-v1-nu-iv1?auditContext=thumbnail',
    alt: 'Presentation of child-safety frameworks to administrators',
    eventId: 'tcnn-partnership-2026',
    eventTitle: 'Official Partnership with TCNN',
    date: 'May 2026',
    year: 2026,
    location: 'TCNN Bukuru, Plateau State',
    aspectRatio: 'landscape'
  },
  {
    id: 'gd-22',
    src: 'https://drive.google.com/u/0/drive-usercontent/125herEkgZx-P51qivVquIxeQiaB2eKHE=w400-h380-p-k-rw-v1-nu-iv1?auditContext=thumbnail',
    alt: 'TCNN youth workshop focusing on boundary safety guidelines',
    eventId: 'tcnn-partnership-2026',
    eventTitle: 'Official Partnership with TCNN',
    date: 'May 2026',
    year: 2026,
    location: 'TCNN Bukuru, Plateau State',
    aspectRatio: 'landscape'
  },
  {
    id: 'gd-23',
    src: 'https://drive.google.com/u/0/drive-usercontent/1fghQWIVTwG1aBWZj7RJBJ_wAax2f5rMU=w400-h380-p-k-rw-v1-nu-iv1?auditContext=thumbnail',
    alt: 'TCNN students and staff listing to key address',
    eventId: 'tcnn-partnership-2026',
    eventTitle: 'Official Partnership with TCNN',
    date: 'May 2026',
    year: 2026,
    location: 'TCNN Bukuru, Plateau State',
    aspectRatio: 'landscape'
  },
  {
    id: 'gd-24',
    src: 'https://drive.google.com/u/0/drive-usercontent/1yduvzEKCCLBnqhG34yxFyAPl9XpQEwpU=w400-h380-p-k-rw-v1-nu-iv1?auditContext=thumbnail',
    alt: 'Mentoring session happening in TCNN classroom circles',
    eventId: 'tcnn-partnership-2026',
    eventTitle: 'Official Partnership with TCNN',
    date: 'May 2026',
    year: 2026,
    location: 'TCNN Bukuru, Plateau State',
    aspectRatio: 'landscape'
  },
  {
    id: 'gd-25',
    src: 'https://drive.google.com/u/0/drive-usercontent/1wNMnSe2TFnaRPk9w91NNWsnQG0jTLrig=w400-h380-p-k-rw-v1-nu-iv1?auditContext=thumbnail',
    alt: 'Healthy communication and relationships focus seminar',
    eventId: 'tcnn-partnership-2026',
    eventTitle: 'Official Partnership with TCNN',
    date: 'May 2026',
    year: 2026,
    location: 'TCNN Bukuru, Plateau State',
    aspectRatio: 'landscape'
  },
  {
    id: 'gd-26',
    src: 'https://drive.google.com/u/0/drive-usercontent/1qWidQKE5CSJaqtdN0bdhbcNQY_o5oj7n=w400-h380-p-k-rw-v1-nu-iv1?auditContext=thumbnail',
    alt: 'Volunteers discussing community outreach cycles',
    eventId: 'tcnn-partnership-2026',
    eventTitle: 'Official Partnership with TCNN',
    date: 'May 2026',
    year: 2026,
    location: 'TCNN Bukuru, Plateau State',
    aspectRatio: 'landscape'
  },
  {
    id: 'gd-27',
    src: 'https://drive.google.com/u/0/drive-usercontent/1RuYmw-c6W03ZLlIP0ABL4EihHiCncmWX=w400-h380-p-k-rw-v1-nu-iv1?auditContext=thumbnail',
    alt: 'Girls receiving educational and hygiene support kits',
    eventId: 'tcnn-partnership-2026',
    eventTitle: 'Official Partnership with TCNN',
    date: 'May 2026',
    year: 2026,
    location: 'TCNN Bukuru, Plateau State',
    aspectRatio: 'landscape'
  },
  {
    id: 'gd-28',
    src: 'https://drive.google.com/u/0/drive-usercontent/1L1fBmvBk5RIZRkZ8TqMiOGuZPlktvImB=w400-h380-p-k-rw-v1-nu-iv1?auditContext=thumbnail',
    alt: 'Launch of the safety helpdesk network inside TCNN campus',
    eventId: 'tcnn-partnership-2026',
    eventTitle: 'Official Partnership with TCNN',
    date: 'May 2026',
    year: 2026,
    location: 'TCNN Bukuru, Plateau State',
    aspectRatio: 'landscape'
  },
  {
    id: 'gd-29',
    src: 'https://drive.google.com/u/0/drive-usercontent/1Avn0lnyCgL_AgkvT9TmMi4teNmyozfLB=w400-h380-p-k-rw-v1-nu-iv1?auditContext=thumbnail',
    alt: 'Workshop participants in collaborative dialogue',
    eventId: 'tcnn-partnership-2026',
    eventTitle: 'Official Partnership with TCNN',
    date: 'May 2026',
    year: 2026,
    location: 'TCNN Bukuru, Plateau State',
    aspectRatio: 'landscape'
  },
  {
    id: 'gd-30',
    src: 'https://drive.google.com/u/0/drive-usercontent/18DQx50eDk_WUYSMWEarjMEQuUDt5wL0j=w400-h380-p-k-rw-v1-nu-iv1?auditContext=thumbnail',
    alt: 'Advocacy training seminar at TCNN auditorium',
    eventId: 'tcnn-partnership-2026',
    eventTitle: 'Official Partnership with TCNN',
    date: 'May 2026',
    year: 2026,
    location: 'TCNN Bukuru, Plateau State',
    aspectRatio: 'landscape'
  },
  {
    id: 'gd-31',
    src: 'https://drive.google.com/u/0/drive-usercontent/1yHGEK8YyaJTCbfc4hbMVVthcdm4qYULD=w400-h380-p-k-rw-v1-nu-iv1?auditContext=thumbnail',
    alt: 'Reproductive health and legal support presentation slides',
    eventId: 'tcnn-partnership-2026',
    eventTitle: 'Official Partnership with TCNN',
    date: 'May 2026',
    year: 2026,
    location: 'TCNN Bukuru, Plateau State',
    aspectRatio: 'landscape'
  },
  {
    id: 'gd-32',
    src: 'https://drive.google.com/u/0/drive-usercontent/1vOai_0IKUHb3JNxy-Xd696YVp3689GIm=w400-h380-p-k-rw-v1-nu-iv1?auditContext=thumbnail',
    alt: 'Group debate and workshops among youth leaders',
    eventId: 'tcnn-partnership-2026',
    eventTitle: 'Official Partnership with TCNN',
    date: 'May 2026',
    year: 2026,
    location: 'TCNN Bukuru, Plateau State',
    aspectRatio: 'landscape'
  },
  {
    id: 'gd-33',
    src: 'https://drive.google.com/u/0/drive-usercontent/1wAKAZweKtuf9VnebMCwmRH1awaL1-AB2=w400-h380-p-k-rw-v1-nu-iv1?auditContext=thumbnail',
    alt: 'ECJAPI founder presenting safe spaces outline to TCNN',
    eventId: 'tcnn-partnership-2026',
    eventTitle: 'Official Partnership with TCNN',
    date: 'May 2026',
    year: 2026,
    location: 'TCNN Bukuru, Plateau State',
    aspectRatio: 'landscape'
  },
  {
    id: 'gd-34',
    src: 'https://drive.google.com/u/0/drive-usercontent/1JqzLafM27QGZ9aOuhuK9PMbqE6jK7yKC=w400-h380-p-k-rw-v1-nu-iv1?auditContext=thumbnail',
    alt: 'Staff and administrators posing together for the signing',
    eventId: 'tcnn-partnership-2026',
    eventTitle: 'Official Partnership with TCNN',
    date: 'May 2026',
    year: 2026,
    location: 'TCNN Bukuru, Plateau State',
    aspectRatio: 'landscape'
  },
  {
    id: 'gd-35',
    src: 'https://drive.google.com/u/0/drive-usercontent/1t9OYPyfcJNRJGeqUfxxbZmDid8yDmzd9=w400-h380-p-k-rw-v1-nu-iv1?auditContext=thumbnail',
    alt: 'Interactive exercises focusing on child safety models',
    eventId: 'tcnn-partnership-2026',
    eventTitle: 'Official Partnership with TCNN',
    date: 'May 2026',
    year: 2026,
    location: 'TCNN Bukuru, Plateau State',
    aspectRatio: 'landscape'
  },
  {
    id: 'gd-36',
    src: 'https://drive.google.com/u/0/drive-usercontent/1qll7QLO8_oIItOEe7_OQJ9zgnz0Lz2kq=w400-h380-p-k-rw-v1-nu-iv1?auditContext=thumbnail',
    alt: 'Presenters answering student counseling questions',
    eventId: 'tcnn-partnership-2026',
    eventTitle: 'Official Partnership with TCNN',
    date: 'May 2026',
    year: 2026,
    location: 'TCNN Bukuru, Plateau State',
    aspectRatio: 'landscape'
  },
  {
    id: 'gd-37',
    src: 'https://drive.google.com/u/0/drive-usercontent/1bMIngf4P64y0bGfHjSTawtIHatZyGnI5=w400-h380-p-k-rw-v1-nu-iv1?auditContext=thumbnail',
    alt: 'Joint safety advisory panel at TCNN campus library hall',
    eventId: 'tcnn-partnership-2026',
    eventTitle: 'Official Partnership with TCNN',
    date: 'May 2026',
    year: 2026,
    location: 'TCNN Bukuru, Plateau State',
    aspectRatio: 'landscape'
  },
  {
    id: 'gd-38',
    src: 'https://drive.google.com/u/0/drive-usercontent/1uhQ1I8eMT9-SBtRQcv32hvJ_f6ZdBHWO=w400-h380-p-k-rw-v1-nu-iv1?auditContext=thumbnail',
    alt: 'Focus groups detailing joint child rights action projects',
    eventId: 'tcnn-partnership-2026',
    eventTitle: 'Official Partnership with TCNN',
    date: 'May 2026',
    year: 2026,
    location: 'TCNN Bukuru, Plateau State',
    aspectRatio: 'landscape'
  },
  {
    id: 'gd-39',
    src: 'https://drive.google.com/u/0/drive-usercontent/1Uq0aiqYM1NwfgFwC9rhNKIvt9KtOHoR2=w400-h380-p-k-rw-v1-nu-iv1?auditContext=thumbnail',
    alt: 'TCNN students reviewing reproductive health booklets',
    eventId: 'tcnn-partnership-2026',
    eventTitle: 'Official Partnership with TCNN',
    date: 'May 2026',
    year: 2026,
    location: 'TCNN Bukuru, Plateau State',
    aspectRatio: 'landscape'
  },
  {
    id: 'gd-40',
    src: 'https://drive.google.com/u/0/drive-usercontent/1JPIwmX0a3z1rVXtrlrLbbMImHf21b3Bz=w400-h380-p-k-rw-v1-nu-iv1?auditContext=thumbnail',
    alt: 'TCNN collaboration official banner group shot',
    eventId: 'tcnn-partnership-2026',
    eventTitle: 'Official Partnership with TCNN',
    date: 'May 2026',
    year: 2026,
    location: 'TCNN Bukuru, Plateau State',
    aspectRatio: 'landscape'
  },
  {
    id: 'gd-41',
    src: 'https://drive.google.com/u/0/drive-usercontent/1OfaxzQU9alevYynWOkLXZMd18RTyu7Dg=w400-h380-p-k-rw-v1-nu-iv1?auditContext=thumbnail',
    alt: 'Organizers and TCNN student network officers',
    eventId: 'tcnn-partnership-2026',
    eventTitle: 'Official Partnership with TCNN',
    date: 'May 2026',
    year: 2026,
    location: 'TCNN Bukuru, Plateau State',
    aspectRatio: 'landscape'
  },
  {
    id: 'gd-42',
    src: 'https://drive.google.com/u/0/drive-usercontent/1dxZbHzOa8FTziA_T7Ej0Mah-fpZUsnj1=w400-h380-p-k-rw-v1-nu-iv1?auditContext=thumbnail',
    alt: 'Joint safety awareness signing and launch forum',
    eventId: 'tcnn-partnership-2026',
    eventTitle: 'Official Partnership with TCNN',
    date: 'May 2026',
    year: 2026,
    location: 'TCNN Bukuru, Plateau State',
    aspectRatio: 'landscape'
  },
  {
    id: 'gd-43',
    src: 'https://drive.google.com/u/0/drive-usercontent/1hvI1m9XPpRTOBcepOyVN6dRhzZWBVwEe=w400-h380-p-k-rw-v1-nu-iv1?auditContext=thumbnail',
    alt: 'TCNN community leaders focus groups',
    eventId: 'tcnn-partnership-2026',
    eventTitle: 'Official Partnership with TCNN',
    date: 'May 2026',
    year: 2026,
    location: 'TCNN Bukuru, Plateau State',
    aspectRatio: 'landscape'
  },
  {
    id: 'gd-44',
    src: 'https://drive.google.com/u/0/drive-usercontent/1x3Lvkvto9npxdFmIGnFDk8iDHuqfZKv4=w400-h380-p-k-rw-v1-nu-iv1?auditContext=thumbnail',
    alt: 'Close-up of participant taking part in the seminar',
    eventId: 'tcnn-partnership-2026',
    eventTitle: 'Official Partnership with TCNN',
    date: 'May 2026',
    year: 2026,
    location: 'TCNN Bukuru, Plateau State',
    aspectRatio: 'landscape'
  },
  {
    id: 'gd-45',
    src: 'https://drive.google.com/u/0/drive-usercontent/1Mhh9AbefrVzURrrxIrX-dkG0FeJ-zvOr=w400-h380-p-k-rw-v1-nu-iv1?auditContext=thumbnail',
    alt: 'TCNN administrators and ECJAPI founders group photo',
    eventId: 'tcnn-partnership-2026',
    eventTitle: 'Official Partnership with TCNN',
    date: 'May 2026',
    year: 2026,
    location: 'TCNN Bukuru, Plateau State',
    aspectRatio: 'landscape'
  },
  {
    id: 'gd-46',
    src: 'https://drive.google.com/u/0/drive-usercontent/14VdGJ5Hi_URLKoVnXmi9b4LFKT2jwRLx=w400-h380-p-k-rw-v1-nu-iv1?auditContext=thumbnail',
    alt: 'Legal guidelines and victim support center overview',
    eventId: 'tcnn-partnership-2026',
    eventTitle: 'Official Partnership with TCNN',
    date: 'May 2026',
    year: 2026,
    location: 'TCNN Bukuru, Plateau State',
    aspectRatio: 'landscape'
  },
  {
    id: 'gd-47',
    src: 'https://drive.google.com/u/0/drive-usercontent/1UkI9J1cFUtYgtjUuPvW7houTRDiHz_0w=w400-h380-p-k-rw-v1-nu-iv1?auditContext=thumbnail',
    alt: 'Hygiene packs display and launch at TCNN center',
    eventId: 'tcnn-partnership-2026',
    eventTitle: 'Official Partnership with TCNN',
    date: 'May 2026',
    year: 2026,
    location: 'TCNN Bukuru, Plateau State',
    aspectRatio: 'landscape'
  },
  {
    id: 'gd-48',
    src: 'https://drive.google.com/u/0/drive-usercontent/1b3o3TnyLEib2TiKVzfWEvJPwEkfChGPN=w400-h380-p-k-rw-v1-nu-iv1?auditContext=thumbnail',
    alt: 'Advocacy training forum debate sessions',
    eventId: 'tcnn-partnership-2026',
    eventTitle: 'Official Partnership with TCNN',
    date: 'May 2026',
    year: 2026,
    location: 'TCNN Bukuru, Plateau State',
    aspectRatio: 'landscape'
  },
  {
    id: 'gd-49',
    src: 'https://drive.google.com/u/0/drive-usercontent/16PeWN1Bolr3dCSpFYV-OT2bGWrRUVAZB=w400-h380-p-k-rw-v1-nu-iv1?auditContext=thumbnail',
    alt: 'Seminar distribution session detail for student leaders',
    eventId: 'tcnn-partnership-2026',
    eventTitle: 'Official Partnership with TCNN',
    date: 'May 2026',
    year: 2026,
    location: 'TCNN Bukuru, Plateau State',
    aspectRatio: 'landscape'
  },
  {
    id: 'gd-50',
    src: 'https://drive.google.com/u/0/drive-usercontent/17To9gvUrqBm1Jez0Syw4cV086AvsmPPR=w400-h380-p-k-rw-v1-nu-iv1?auditContext=thumbnail',
    alt: 'Partnership launch commemorative photograph',
    eventId: 'tcnn-partnership-2026',
    eventTitle: 'Official Partnership with TCNN',
    date: 'May 2026',
    year: 2026,
    location: 'TCNN Bukuru, Plateau State',
    aspectRatio: 'landscape'
  },

  // 1.2 First Time Lunch - Female Stable Hands (July 2026) - Local Images
  {
    id: 'sh-1',
    src: '/first_time_lunch_female_stable_hands_in_nigeria/WhatsApp%20Image%202026-07-08%20at%2011.13.37.jpeg',
    alt: 'Group portrait of the female stable hands during the lunch program',
    eventId: 'first-time-lunch-stable-hands-2026',
    eventTitle: 'First Time Lunch - Female Stable Hands',
    date: 'July 8, 2026',
    year: 2026,
    location: 'Plateau State, Nigeria',
    aspectRatio: 'landscape'
  },
  {
    id: 'sh-2',
    src: '/first_time_lunch_female_stable_hands_in_nigeria/WhatsApp%20Image%202026-07-08%20at%2011.13.38.jpeg',
    alt: 'Mentors discussing biological health education with attendees',
    eventId: 'first-time-lunch-stable-hands-2026',
    eventTitle: 'First Time Lunch - Female Stable Hands',
    date: 'July 8, 2026',
    year: 2026,
    location: 'Plateau State, Nigeria',
    aspectRatio: 'landscape'
  },
  {
    id: 'sh-3',
    src: '/first_time_lunch_female_stable_hands_in_nigeria/WhatsApp%20Image%202026-07-08%20at%2011.13.39.jpeg',
    alt: 'Attendees sharing experiences and challenges faced in stable roles',
    eventId: 'first-time-lunch-stable-hands-2026',
    eventTitle: 'First Time Lunch - Female Stable Hands',
    date: 'July 8, 2026',
    year: 2026,
    location: 'Plateau State, Nigeria',
    aspectRatio: 'landscape'
  },
  {
    id: 'sh-4',
    src: '/first_time_lunch_female_stable_hands_in_nigeria/WhatsApp%20Image%202026-07-08%20at%2011.13.40.jpeg',
    alt: 'Providing lunch boxes and care kits to the girls',
    eventId: 'first-time-lunch-stable-hands-2026',
    eventTitle: 'First Time Lunch - Female Stable Hands',
    date: 'July 8, 2026',
    year: 2026,
    location: 'Plateau State, Nigeria',
    aspectRatio: 'landscape'
  },
  {
    id: 'sh-5',
    src: '/first_time_lunch_female_stable_hands_in_nigeria/WhatsApp%20Image%202026-07-08%20at%2011.13.42.jpeg',
    alt: 'Interactive safety boundaries seminar session',
    eventId: 'first-time-lunch-stable-hands-2026',
    eventTitle: 'First Time Lunch - Female Stable Hands',
    date: 'July 8, 2026',
    year: 2026,
    location: 'Plateau State, Nigeria',
    aspectRatio: 'landscape'
  },
  {
    id: 'sh-6',
    src: '/first_time_lunch_female_stable_hands_in_nigeria/WhatsApp%20Image%202026-07-08%20at%2011.13.43.jpeg',
    alt: 'Speakers presenting consent models to stable workers',
    eventId: 'first-time-lunch-stable-hands-2026',
    eventTitle: 'First Time Lunch - Female Stable Hands',
    date: 'July 8, 2026',
    year: 2026,
    location: 'Plateau State, Nigeria',
    aspectRatio: 'landscape'
  },
  {
    id: 'sh-7',
    src: '/first_time_lunch_female_stable_hands_in_nigeria/WhatsApp%20Image%202026-07-08%20at%2011.13.44.jpeg',
    alt: 'Female stable hands laughing and sharing happy moments',
    eventId: 'first-time-lunch-stable-hands-2026',
    eventTitle: 'First Time Lunch - Female Stable Hands',
    date: 'July 8, 2026',
    year: 2026,
    location: 'Plateau State, Nigeria',
    aspectRatio: 'landscape'
  },
  {
    id: 'sh-8',
    src: '/first_time_lunch_female_stable_hands_in_nigeria/WhatsApp%20Image%202026-07-08%20at%2011.13.45.jpeg',
    alt: 'Outreach coordinators distributing hygienic resources',
    eventId: 'first-time-lunch-stable-hands-2026',
    eventTitle: 'First Time Lunch - Female Stable Hands',
    date: 'July 8, 2026',
    year: 2026,
    location: 'Plateau State, Nigeria',
    aspectRatio: 'landscape'
  },
  {
    id: 'sh-9',
    src: '/first_time_lunch_female_stable_hands_in_nigeria/WhatsApp%20Image%202026-07-08%20at%2011.13.46.jpeg',
    alt: 'Mentoring circles answering health questions',
    eventId: 'first-time-lunch-stable-hands-2026',
    eventTitle: 'First Time Lunch - Female Stable Hands',
    date: 'July 8, 2026',
    year: 2026,
    location: 'Plateau State, Nigeria',
    aspectRatio: 'landscape'
  },
  {
    id: 'sh-10',
    src: '/first_time_lunch_female_stable_hands_in_nigeria/WhatsApp%20Image%202026-07-08%20at%2011.13.47.jpeg',
    alt: 'Female stable hands during self-esteem and values talks',
    eventId: 'first-time-lunch-stable-hands-2026',
    eventTitle: 'First Time Lunch - Female Stable Hands',
    date: 'July 8, 2026',
    year: 2026,
    location: 'Plateau State, Nigeria',
    aspectRatio: 'landscape'
  },
  {
    id: 'sh-11',
    src: '/first_time_lunch_female_stable_hands_in_nigeria/WhatsApp%20Image%202026-07-08%20at%2011.13.48.jpeg',
    alt: 'A volunteer scientist discussing menstrual hygiene cycles',
    eventId: 'first-time-lunch-stable-hands-2026',
    eventTitle: 'First Time Lunch - Female Stable Hands',
    date: 'July 8, 2026',
    year: 2026,
    location: 'Plateau State, Nigeria',
    aspectRatio: 'landscape'
  },
  {
    id: 'sh-12',
    src: '/first_time_lunch_female_stable_hands_in_nigeria/WhatsApp%20Image%202026-07-08%20at%2011.13.50.jpeg',
    alt: 'Group discussion and lunch overview session',
    eventId: 'first-time-lunch-stable-hands-2026',
    eventTitle: 'First Time Lunch - Female Stable Hands',
    date: 'July 8, 2026',
    year: 2026,
    location: 'Plateau State, Nigeria',
    aspectRatio: 'landscape'
  },

  // 2. World Menstrual Health Day Campaign (May 2026) - Local Images
  {
    id: 'limg-1',
    src: '/jen/empowher_choices.japi_1783442692847.jpeg',
    alt: 'EmpowHer Choices Padded Girl Campaign Presentation',
    eventId: 'padded-girl-campaign-2026',
    eventTitle: 'De-Stigmatizing Menstrual Development, Dismantles Rape Culture Campaign',
    date: 'May 28, 2026',
    year: 2026,
    location: 'Schools across Bukuru & Zawan',
    aspectRatio: 'landscape'
  },
  {
    id: 'limg-2',
    src: '/jen/empowher_choices.japi_1783442969963.jpeg',
    alt: 'Padded Girl Awareness Session in Schools',
    eventId: 'padded-girl-campaign-2026',
    eventTitle: 'De-Stigmatizing Menstrual Development, Dismantles Rape Culture Campaign',
    date: 'May 28, 2026',
    year: 2026,
    location: 'Schools across Bukuru & Zawan',
    aspectRatio: 'landscape'
  },
  {
    id: 'limg-3',
    src: '/jen/empowher_choices.japi_1783442969965.jpeg',
    alt: 'Students Participating in Menstrual Health Seminar',
    eventId: 'padded-girl-campaign-2026',
    eventTitle: 'De-Stigmatizing Menstrual Development, Dismantles Rape Culture Campaign',
    date: 'May 28, 2026',
    year: 2026,
    location: 'Schools across Bukuru & Zawan',
    aspectRatio: 'landscape'
  },
  {
    id: 'limg-4',
    src: '/jen/manlikemagwa_1783442525426.jpeg',
    alt: 'Padded Girl Interactive Workshop',
    eventId: 'padded-girl-campaign-2026',
    eventTitle: 'De-Stigmatizing Menstrual Development, Dismantles Rape Culture Campaign',
    date: 'May 28, 2026',
    year: 2026,
    location: 'Schools across Bukuru & Zawan',
    aspectRatio: 'landscape'
  },
  {
    id: 'limg-5',
    src: '/jen/manlikemagwa_1783442525427.jpeg',
    alt: 'School outreach group photograph',
    eventId: 'padded-girl-campaign-2026',
    eventTitle: 'De-Stigmatizing Menstrual Development, Dismantles Rape Culture Campaign',
    date: 'May 28, 2026',
    year: 2026,
    location: 'Schools across Bukuru & Zawan',
    aspectRatio: 'landscape'
  },
  {
    id: 'limg-6',
    src: '/jen/manlikemagwa_1783442594266.jpeg',
    alt: 'Educators and Speakers at Hope High Academy',
    eventId: 'padded-girl-campaign-2026',
    eventTitle: 'De-Stigmatizing Menstrual Development, Dismantles Rape Culture Campaign',
    date: 'May 28, 2026',
    year: 2026,
    location: 'Schools across Bukuru & Zawan',
    aspectRatio: 'landscape'
  },
  {
    id: 'limg-7',
    src: '/jen/nikurai_1783442755146.jpeg',
    alt: 'Founder Ms. Jennifer Nikurai Maton addressing students',
    eventId: 'padded-girl-campaign-2026',
    eventTitle: 'De-Stigmatizing Menstrual Development, Dismantles Rape Culture Campaign',
    date: 'May 28, 2026',
    year: 2026,
    location: 'Schools across Bukuru & Zawan',
    aspectRatio: 'landscape'
  },
  {
    id: 'limg-8',
    src: '/jen/nikurai_1783442800013.jpeg',
    alt: 'Biodegradable Sanitary Pads Demonstration',
    eventId: 'padded-girl-campaign-2026',
    eventTitle: 'De-Stigmatizing Menstrual Development, Dismantles Rape Culture Campaign',
    date: 'May 28, 2026',
    year: 2026,
    location: 'Schools across Bukuru & Zawan',
    aspectRatio: 'landscape'
  },

  // 3. How the Story Began (2024) - Local Images
  {
    id: 'story-1',
    src: '/how_the_story_began/WhatsApp%20Image%202026-07-08%20at%2011.10.14.jpeg',
    alt: 'The initial grassroots seminar presenting the initiative',
    eventId: 'how-the-story-began-2024',
    eventTitle: 'How the Story Began',
    date: 'May 2024',
    year: 2024,
    location: 'Bukuru, Plateau State',
    aspectRatio: 'landscape'
  },
  {
    id: 'story-2',
    src: '/how_the_story_began/WhatsApp%20Image%202026-07-08%20at%2011.10.16.jpeg',
    alt: 'First group of girls attending the counseling workshop',
    eventId: 'how-the-story-began-2024',
    eventTitle: 'How the Story Began',
    date: 'May 2024',
    year: 2024,
    location: 'Bukuru, Plateau State',
    aspectRatio: 'landscape'
  },
  {
    id: 'story-3',
    src: '/how_the_story_began/WhatsApp%20Image%202026-07-08%20at%2011.10.17%20(1).jpeg',
    alt: 'Advocacy circle discussing girl child education rights',
    eventId: 'how-the-story-began-2024',
    eventTitle: 'How the Story Began',
    date: 'May 2024',
    year: 2024,
    location: 'Bukuru, Plateau State',
    aspectRatio: 'landscape'
  },
  {
    id: 'story-4',
    src: '/how_the_story_began/WhatsApp%20Image%202026-07-08%20at%2011.10.17.jpeg',
    alt: 'Organizing the very first sanitary resource distributions',
    eventId: 'how-the-story-began-2024',
    eventTitle: 'How the Story Began',
    date: 'May 2024',
    year: 2024,
    location: 'Bukuru, Plateau State',
    aspectRatio: 'landscape'
  },
  {
    id: 'story-5',
    src: '/how_the_story_began/WhatsApp%20Image%202026-07-08%20at%2011.10.35.jpeg',
    alt: 'Community leaders and volunteers gather for initial launch',
    eventId: 'how-the-story-began-2024',
    eventTitle: 'How the Story Began',
    date: 'May 2024',
    year: 2024,
    location: 'Bukuru, Plateau State',
    aspectRatio: 'landscape'
  },
  {
    id: 'story-6',
    src: '/how_the_story_began/WhatsApp%20Image%202026-07-08%20at%2011.10.36.jpeg',
    alt: 'Students smiling during the inaugural self-worth workshop',
    eventId: 'how-the-story-began-2024',
    eventTitle: 'How the Story Began',
    date: 'May 2024',
    year: 2024,
    location: 'Bukuru, Plateau State',
    aspectRatio: 'landscape'
  },
  {
    id: 'story-7',
    src: '/how_the_story_began/WhatsApp%20Image%202026-07-08%20at%2011.10.37%20(1).jpeg',
    alt: 'Interactive discussion on child abuse prevention protocols',
    eventId: 'how-the-story-began-2024',
    eventTitle: 'How the Story Began',
    date: 'May 2024',
    year: 2024,
    location: 'Bukuru, Plateau State',
    aspectRatio: 'landscape'
  },
  {
    id: 'story-8',
    src: '/how_the_story_began/WhatsApp%20Image%202026-07-08%20at%2011.10.37%20(2).jpeg',
    alt: 'Our founders posing with the first seminar attendees',
    eventId: 'how-the-story-began-2024',
    eventTitle: 'How the Story Began',
    date: 'May 2024',
    year: 2024,
    location: 'Bukuru, Plateau State',
    aspectRatio: 'landscape'
  },
  {
    id: 'story-9',
    src: '/how_the_story_began/WhatsApp%20Image%202026-07-08%20at%2011.10.54.jpeg',
    alt: 'Inaugural workshop banner group shot',
    eventId: 'how-the-story-began-2024',
    eventTitle: 'How the Story Began',
    date: 'May 2024',
    year: 2024,
    location: 'Bukuru, Plateau State',
    aspectRatio: 'landscape'
  },
  {
    id: 'story-10',
    src: '/how_the_story_began/WhatsApp%20Image%202026-07-08%20at%2011.11.26.jpeg',
    alt: 'Group portrait commemorating the launch of ECJAPI',
    eventId: 'how-the-story-began-2024',
    eventTitle: 'How the Story Began',
    date: 'May 2024',
    year: 2024,
    location: 'Bukuru, Plateau State',
    aspectRatio: 'landscape'
  },
  {
    id: 'horsemanship-still-1',
    src: '/new_stills/rawuta_instagram.jpg',
    alt: "Ms. Rawuta Bishara, certified female stablehand and horsemanship program graduate, in frame",
    eventId: 'horsemanship-closing-ceremony-2025',
    eventTitle: 'Stablehand & Horsemanship Closing Ceremony & Fundraiser',
    date: 'January 9-11, 2025',
    year: 2025,
    location: 'Plateau State, Nigeria',
    aspectRatio: 'portrait'
  },
  {
    id: 'horsemanship-still-2',
    src: '/new_stills/WhatsApp%20Image%202026-07-13%20at%2023.19.41.jpeg',
    alt: "Seasoned and newly scouted female polo players from across Nigeria gathered for the groundbreaking showcase",
    eventId: 'horsemanship-closing-ceremony-2025',
    eventTitle: 'Stablehand & Horsemanship Closing Ceremony & Fundraiser',
    date: 'January 9-11, 2025',
    year: 2025,
    location: 'Plateau State, Nigeria',
    aspectRatio: 'landscape'
  },
  {
    id: 'horsemanship-still-3',
    src: '/new_stills/WhatsApp%20Image%202026-07-14%20at%2010.17.05%20%289%29.jpeg',
    alt: "Amazonian Reins vs Rein Rebels - Nigeria's first ever All-Female Polo game match action",
    eventId: 'horsemanship-closing-ceremony-2025',
    eventTitle: 'Stablehand & Horsemanship Closing Ceremony & Fundraiser',
    date: 'January 9-11, 2025',
    year: 2025,
    location: 'Plateau State, Nigeria',
    aspectRatio: 'landscape'
  },
  {
    id: 'horsemanship-still-4',
    src: '/new_stills/WhatsApp%20Image%202026-07-14%20at%2010.17.29%20%2814%29.jpeg',
    alt: "Official presentation of the Rein Rebels team, representing the Equestrian League for ECJAPI",
    eventId: 'horsemanship-closing-ceremony-2025',
    eventTitle: 'Stablehand & Horsemanship Closing Ceremony & Fundraiser',
    date: 'January 9-11, 2025',
    year: 2025,
    location: 'Plateau State, Nigeria',
    aspectRatio: 'portrait'
  },
  {
    id: 'horsemanship-still-5',
    src: '/new_stills/WhatsApp%20Image%202026-07-14%20at%2010.17.29%20%2822%29.jpeg',
    alt: "All-female commentators and MCs guiding the closing ceremony and fundraiser",
    eventId: 'horsemanship-closing-ceremony-2025',
    eventTitle: 'Stablehand & Horsemanship Closing Ceremony & Fundraiser',
    date: 'January 9-11, 2025',
    year: 2025,
    location: 'Plateau State, Nigeria',
    aspectRatio: 'landscape'
  },
  {
    id: 'horsemanship-still-6',
    src: '/new_stills/WhatsApp%20Image%202026-07-14%20at%2010.17.29%20%2830%29.jpeg',
    alt: "Female stablehand training graduates preparing the horses before the exhibition game",
    eventId: 'horsemanship-closing-ceremony-2025',
    eventTitle: 'Stablehand & Horsemanship Closing Ceremony & Fundraiser',
    date: 'January 9-11, 2025',
    year: 2025,
    location: 'Plateau State, Nigeria',
    aspectRatio: 'landscape'
  },
  {
    id: 'horsemanship-still-7',
    src: '/new_stills/WhatsApp%20Image%202026-07-14%20at%2010.17.29.jpeg',
    alt: "Flag bearers leading the parade during the opening of the All-Female Sports & Service Showcase",
    eventId: 'horsemanship-closing-ceremony-2025',
    eventTitle: 'Stablehand & Horsemanship Closing Ceremony & Fundraiser',
    date: 'January 9-11, 2025',
    year: 2025,
    location: 'Plateau State, Nigeria',
    aspectRatio: 'portrait'
  },
  {
    id: 'horsemanship-still-8',
    src: '/new_stills/WhatsApp%20Image%202026-07-14%20at%2010.17.30%20%2817%29.jpeg',
    alt: "Umpire and match coordinators, all female, preparing for the historic polo match kickoff",
    eventId: 'horsemanship-closing-ceremony-2025',
    eventTitle: 'Stablehand & Horsemanship Closing Ceremony & Fundraiser',
    date: 'January 9-11, 2025',
    year: 2025,
    location: 'Plateau State, Nigeria',
    aspectRatio: 'landscape'
  },
  {
    id: 'horsemanship-still-9',
    src: '/new_stills/WhatsApp%20Image%202026-07-14%20at%2010.17.30%20%2825%29.jpeg',
    alt: "Amazonian Reins team riders strategic planning session before the game",
    eventId: 'horsemanship-closing-ceremony-2025',
    eventTitle: 'Stablehand & Horsemanship Closing Ceremony & Fundraiser',
    date: 'January 9-11, 2025',
    year: 2025,
    location: 'Plateau State, Nigeria',
    aspectRatio: 'landscape'
  },
  {
    id: 'horsemanship-still-10',
    src: '/new_stills/WhatsApp%20Image%202026-07-14%20at%2010.17.30%20%2833%29.jpeg',
    alt: "Crowd and guests supporting the Female Stablehand & Horsemanship Training fundraiser",
    eventId: 'horsemanship-closing-ceremony-2025',
    eventTitle: 'Stablehand & Horsemanship Closing Ceremony & Fundraiser',
    date: 'January 9-11, 2025',
    year: 2025,
    location: 'Plateau State, Nigeria',
    aspectRatio: 'portrait'
  },
  {
    id: 'horsemanship-still-11',
    src: '/new_stills/WhatsApp%20Image%202026-07-14%20at%2010.17.30%20%2841%29.jpeg',
    alt: "Certified female stablehands demonstrating grooming techniques during the ceremony",
    eventId: 'horsemanship-closing-ceremony-2025',
    eventTitle: 'Stablehand & Horsemanship Closing Ceremony & Fundraiser',
    date: 'January 9-11, 2025',
    year: 2025,
    location: 'Plateau State, Nigeria',
    aspectRatio: 'landscape'
  },
  {
    id: 'horsemanship-still-12',
    src: '/new_stills/WhatsApp%20Image%202026-07-14%20at%2010.17.30%20%285%29.jpeg',
    alt: "Action shot of the Rein Rebels attacking during the All-Female Polo Game",
    eventId: 'horsemanship-closing-ceremony-2025',
    eventTitle: 'Stablehand & Horsemanship Closing Ceremony & Fundraiser',
    date: 'January 9-11, 2025',
    year: 2025,
    location: 'Plateau State, Nigeria',
    aspectRatio: 'landscape'
  },
  {
    id: 'horsemanship-still-13',
    src: '/new_stills/WhatsApp%20Image%202026-07-14%20at%2010.17.30%20%2858%29.jpeg',
    alt: "Certified stablehand check-ups and equestrian care demonstration at the closing showcase",
    eventId: 'horsemanship-closing-ceremony-2025',
    eventTitle: 'Stablehand & Horsemanship Closing Ceremony & Fundraiser',
    date: 'January 9-11, 2025',
    year: 2025,
    location: 'Plateau State, Nigeria',
    aspectRatio: 'portrait'
  },
  {
    id: 'horsemanship-still-14',
    src: '/new_stills/WhatsApp%20Image%202026-07-14%20at%2010.17.30%20%2866%29.jpeg',
    alt: "Polo players from the Amazonian Reins showcasing high-energy equestrian skills",
    eventId: 'horsemanship-closing-ceremony-2025',
    eventTitle: 'Stablehand & Horsemanship Closing Ceremony & Fundraiser',
    date: 'January 9-11, 2025',
    year: 2025,
    location: 'Plateau State, Nigeria',
    aspectRatio: 'landscape'
  },
  {
    id: 'horsemanship-still-15',
    src: '/new_stills/WhatsApp%20Image%202026-07-14%20at%2010.17.30%20%2874%29.jpeg',
    alt: "All-female bouncers and security team managing the fundraiser event venue",
    eventId: 'horsemanship-closing-ceremony-2025',
    eventTitle: 'Stablehand & Horsemanship Closing Ceremony & Fundraiser',
    date: 'January 9-11, 2025',
    year: 2025,
    location: 'Plateau State, Nigeria',
    aspectRatio: 'landscape'
  },
  {
    id: 'horsemanship-still-16',
    src: '/new_stills/WhatsApp%20Image%202026-07-14%20at%2010.17.30%20%2882%29.jpeg',
    alt: "Founder Nikurai Jennifer Maton alongside newly trained stablehands and polo players",
    eventId: 'horsemanship-closing-ceremony-2025',
    eventTitle: 'Stablehand & Horsemanship Closing Ceremony & Fundraiser',
    date: 'January 9-11, 2025',
    year: 2025,
    location: 'Plateau State, Nigeria',
    aspectRatio: 'portrait'
  },
  {
    id: 'horsemanship-still-17',
    src: '/new_stills/WhatsApp%20Image%202026-07-14%20at%2010.17.30%20%2890%29.jpeg',
    alt: "Fundraiser event coordinators celebrating the completion of Nigeria's first ever Female Stablehand program",
    eventId: 'horsemanship-closing-ceremony-2025',
    eventTitle: 'Stablehand & Horsemanship Closing Ceremony & Fundraiser',
    date: 'January 9-11, 2025',
    year: 2025,
    location: 'Plateau State, Nigeria',
    aspectRatio: 'landscape'
  },
  {
    id: 'horsemanship-still-18',
    src: '/new_stills/WhatsApp%20Image%202026-07-14%20at%2010.17.30%20%2899%29.jpeg',
    alt: "Group photo of the Amazonian Reins and Rein Rebels teams post-match",
    eventId: 'horsemanship-closing-ceremony-2025',
    eventTitle: 'Stablehand & Horsemanship Closing Ceremony & Fundraiser',
    date: 'January 9-11, 2025',
    year: 2025,
    location: 'Plateau State, Nigeria',
    aspectRatio: 'landscape'
  }
];
